import { StyleSheet } from 'react-native';

/** @param {object} colors Theme palette from `useTheme()`. */
export function createBookingLinkEditStyles(colors, galleryGap) {
  return StyleSheet.create({
    wrap: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 0,
    },
    content: {
      paddingBottom: 28,
    },
    stickyHeaderShell: {
      alignSelf: 'stretch',
      backgroundColor: colors.shell,
      borderBottomColor: colors.border,
      borderBottomWidth: StyleSheet.hairlineWidth,
      elevation: 6,
      marginBottom: 10,
      paddingBottom: 8,
      paddingTop: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      zIndex: 10,
    },
    topActionsCard: {
      alignSelf: 'stretch',
      backgroundColor: colors.cardSurface,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      marginBottom: 0,
      padding: 8,
    },
    topActionsRow: {
      alignSelf: 'stretch',
      flexDirection: 'row',
      gap: 10,
      width: '100%',
    },
    actionCell: {
      flex: 1,
      flexBasis: 0,
      minWidth: 0,
    },
    sectionTitle: {
      color: colors.textSecondary,
      fontSize: 15,
      fontWeight: '600',
      letterSpacing: -0.2,
      marginBottom: 3,
    },
    sectionBody: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: -0.1,
      lineHeight: 17,
      marginBottom: 12,
    },
    coverSurfaceWrap: {
      alignSelf: 'stretch',
      borderRadius: 20,
      overflow: 'hidden',
      width: '100%',
    },
    coverCardPressed: {
      opacity: 0.94,
    },
    coverInnerPressable: {
      overflow: 'hidden',
      width: '100%',
    },
    coverImage: {
      aspectRatio: 16 / 8.2,
      width: '100%',
    },
    coverFallback: {
      alignItems: 'center',
      backgroundColor: colors.shellElevated,
      justifyContent: 'center',
    },
    coverFallbackHint: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '600',
      marginTop: 10,
    },
    coverCta: {
      alignItems: 'center',
      backgroundColor: 'rgba(10,10,10,0.76)',
      borderColor: 'rgba(255,255,255,0.2)',
      borderRadius: 14,
      borderWidth: 1,
      bottom: 12,
      flexDirection: 'row',
      left: 12,
      minHeight: 44,
      paddingHorizontal: 14,
      position: 'absolute',
    },
    coverCtaText: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: '600',
      marginLeft: 8,
    },
    coverCamera: {
      alignItems: 'center',
      backgroundColor: 'rgba(10,10,10,0.76)',
      borderColor: 'rgba(255,255,255,0.2)',
      borderRadius: 12,
      borderWidth: 1,
      bottom: 12,
      height: 40,
      justifyContent: 'center',
      position: 'absolute',
      right: 12,
      width: 40,
    },
    logoSection: {
      marginTop: 18,
    },
    logoSurfaceCard: {
      alignSelf: 'stretch',
      width: '100%',
    },
    logoCardPressable: {
      minHeight: 104,
      width: '100%',
    },
    logoCardPressed: {
      opacity: 0.94,
    },
    logoCardRow: {
      alignItems: 'center',
      flexDirection: 'row',
      width: '100%',
    },
    logoPreviewWrap: {
      alignItems: 'center',
      backgroundColor: colors.border,
      borderColor: colors.borderStrong,
      borderRadius: 44,
      borderWidth: 2,
      height: 88,
      justifyContent: 'center',
      marginRight: 12,
      overflow: 'hidden',
      width: 88,
    },
    logoPreviewImage: {
      height: '100%',
      width: '100%',
    },
    logoInfo: {
      flex: 0.92,
      minWidth: 0,
      paddingRight: 4,
    },
    logoTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 4,
    },
    logoSubtitle: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
    },
    logoAction: {
      alignItems: 'center',
      backgroundColor: colors.shellElevated,
      borderColor: colors.borderStrong,
      borderRadius: 999,
      borderWidth: 1,
      flexShrink: 0,
      height: 38,
      justifyContent: 'center',
      width: 38,
    },
    infoSection: {
      marginTop: 18,
    },
    infoSectionIntro: {
      marginBottom: 10,
    },
    infoField: {
      marginBottom: 14,
    },
    infoFieldLast: {
      marginBottom: 2,
    },
    infoSelectFieldFlushTop: {
      marginTop: 0,
    },
    contactSection: {
      marginTop: 0,
    },
    contactSectionTitle: {
      marginBottom: 10,
    },
    gallerySection: {
      marginTop: 0,
    },
    galleryAddPhotoOuter: {
      alignSelf: 'stretch',
      backgroundColor: colors.shellElevated,
      borderRadius: 20,
      padding: 24,
      width: '100%',
    },
    galleryAddPhotoPressable: {
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    galleryAddPhotoAreaPressed: {
      opacity: 0.94,
    },
    galleryAddStack: {
      alignItems: 'center',
      gap: 10,
      justifyContent: 'center',
      maxWidth: '100%',
    },
    addPhotoTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
      textAlign: 'center',
    },
    addPhotoSubtitle: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
      textAlign: 'center',
    },
    portfolioHeading: {
      color: colors.textSecondary,
      fontSize: 15,
      fontWeight: '600',
      letterSpacing: -0.2,
      marginBottom: 4,
      marginTop: 20,
    },
    portfolioSub: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: -0.1,
      lineHeight: 17,
      marginBottom: 12,
    },
    portfolioGrid: {
      alignContent: 'flex-start',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: galleryGap,
      justifyContent: 'flex-start',
    },
    portfolioTileWrap: {
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      flexGrow: 0,
      flexShrink: 0,
      overflow: 'hidden',
    },
    portfolioTileImage: {
      height: '100%',
      width: '100%',
    },
    portfolioRemove: {
      alignItems: 'center',
      backgroundColor: 'rgba(10,10,10,0.62)',
      borderRadius: 999,
      height: 26,
      justifyContent: 'center',
      position: 'absolute',
      right: 6,
      top: 6,
      width: 26,
    },
    portfolioEmpty: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '500',
      marginTop: 4,
    },
    bioInput: {
      minHeight: 128,
      paddingTop: 12,
      textAlignVertical: 'top',
    },
    divider: {
      backgroundColor: colors.border,
      height: 1,
      marginBottom: 10,
      marginTop: 14,
    },
  });
}
