export const COMPLETE_VISIT_RECEIPT_CONTACT_NEEDED = 'Email or phone needed';

export const COMPLETE_VISIT_RECEIPT_CONTACT_CTA_DETAIL = 'Info needed for Tap to Pay receipt';

export const COMPLETE_VISIT_RECEIPT_CONTACT_ADD_LINK = 'Add email or phone';

export const COMPLETE_VISIT_RECEIPT_CONTACT_DIALOG_TITLE = 'Add contact info';

export const COMPLETE_VISIT_RECEIPT_CONTACT_DIALOG_SUBTITLE =
  'Add an email or phone so we can send a receipt.';

export const COMPLETE_VISIT_RECEIPT_EMAIL_PLACEHOLDER = 'customer@email.com';

export const COMPLETE_VISIT_RECEIPT_PHONE_PLACEHOLDER = '(555) 555-5555';

export const COMPLETE_VISIT_RECEIPT_CONTACT_SAVE_LABEL = 'Save';

export const COMPLETE_VISIT_RECEIPT_CONTACT_INVALID_TOAST = 'Enter a valid email or phone number.';

export const COMPLETE_VISIT_RECEIPT_CONTACT_SAVE_ERROR_TOAST =
  'Could not save contact info. Please try again.';

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_NEEDED}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_NEEDED = COMPLETE_VISIT_RECEIPT_CONTACT_NEEDED;

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_CTA_DETAIL}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_CTA_DETAIL = COMPLETE_VISIT_RECEIPT_CONTACT_CTA_DETAIL;

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_ADD_LINK}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_ADD_LINK = COMPLETE_VISIT_RECEIPT_CONTACT_ADD_LINK;

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_DIALOG_TITLE}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_DIALOG_TITLE =
  COMPLETE_VISIT_RECEIPT_CONTACT_DIALOG_TITLE;

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_DIALOG_SUBTITLE}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_DIALOG_SUBTITLE =
  COMPLETE_VISIT_RECEIPT_CONTACT_DIALOG_SUBTITLE;

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_SAVE_LABEL}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_SAVE_LABEL = COMPLETE_VISIT_RECEIPT_CONTACT_SAVE_LABEL;

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_INVALID_TOAST}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_INVALID_TOAST =
  COMPLETE_VISIT_RECEIPT_CONTACT_INVALID_TOAST;

/** @deprecated Use {@link COMPLETE_VISIT_RECEIPT_CONTACT_SAVE_ERROR_TOAST}. */
export const COMPLETE_VISIT_RECEIPT_EMAIL_SAVE_ERROR_TOAST =
  COMPLETE_VISIT_RECEIPT_CONTACT_SAVE_ERROR_TOAST;
